name:                indent-parser
version:             0.1.0.0
github:              "momohatt/indent-parser-example"
license:             BSD3
author:              "momohatt"
# maintainer:          "momohatt10@gmail.com"
copyright:           "2019 momohatt"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/momohatt/indent-parser-example#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- indents
- mtl
- megaparsec
- text
- parser-combinators

library:
  source-dirs: src

executables:
  indent-parser:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - indent-parser
